name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v7
    
    - name: Compile
      run: make clean && make
      
    - name: Run clang-format check
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y clang-format
        clang-format --dry-run --Werror src/core/*.c src/tools/*/*.c include/*.h

    - name: Test CLI Interfaces
      run: |
        ./bin/knetutils ping -h || true
        ./bin/knetutils arping -h || true
        ./bin/knetutils tcping -h || true
        ./bin/knetutils traceroute -h || true
